### ISSUE TITLE
Doubled comment notifications in recent activity feed

### ISSUE THREAD

**Issue by sabreuse** [wordset/wordset-ui#11]
When I comment on a proposal (as opposed to voting on it), the notifications in the activity feed is doubled, like so:

![](https://cldup.com/ZPBqoHAs40-3000x3000.png)

The two entries have two different IDs. After a page refresh, the duplicate disappears.

**Comment by hcatlin** [comment]
I'm guessing this is `createRecord`, then `save()`... and for some reason the return from `save()` isn't setting the ID. THEN, the pusher push comes in, with the activity, and it inserts it into the same table, not realizing it's a dup.

**Comment by interestinall** [comment]
Lately this seems to only happen to me. No idea why.
