### ISSUE TITLE
More labels needed

### ISSUE THREAD

**Issue by BryanCode** [wordset/wordset-ui#111]
Intransitive and transitive labels would be good for verbs. A mathematics label would also be nice.

**Comment by hcatlin** [comment]
Justin, can you come up with a list of these? I can implement most anything...

**Comment by interestinall** [comment]
How many labels is too many?

For example, it is kind of lame to start definitions with "in Biology" and
the like, but do we want to add all of the sciences as separate labels?

**Comment by interestinall** [comment]
So the consensus is that we don't think adding labels for every scientific discipline is necessary, but we do want to add a label for mathematics. And trans /intrans verbs. Would be cool if we add the verb stuff soon and encourage the label use as we are going through a  big verb fix.
