### ISSUE TITLE
the Help Out button for a finished project hangs indefinitely

### ISSUE THREAD

**Issue by sabreuse** [wordset/wordset-ui#112]
When there are no words in the target list left, but the project isn't yet fully shut down (because of pending words, ongoing discussion, or the like), clicking the Help button on the proposal page should return an informative message. I've hit the GNP page half a dozen times today out of habit, and the button just sits there in its active state, taunting...

**Comment by danielrw7** [comment]
I didn't mean to reference this issue. Sorry!
