### ISSUE TITLE
Fixed definitions aren't always cleared from project lists

### ISSUE THREAD

**Issue by sabreuse** [wordset/wordset-ui#113]
I was just offered https://www.wordset.org/project/parentheses/propose/54bd5678726574239111fc01 as a suggestion in the parentheses project -- note that it doesn't have parentheses, and has a complete and non-gendered sentence. I suspect that it was included in the original search for the parentheses project, and was fixed at a later time by someone coming from some other route. It should have been cleared from the cached parentheses project list at some point, but wasn't.

**Comment by malrase** [comment]
I believe @hcatlin has fixed this – proposals that have been fixed on one project will also be fixed in other appropriate projects.
