### ISSUE TITLE
Issue with editing proposal

### ISSUE THREAD

**Issue by lasseebert** [wordset/wordset-ui#12]
I was editing a proposal I had submitted earlier and nothing happened.

Steps:
 - On the proposal page (`/proposal/:id`) I click Edit
 - Make some corrections
 - Click Submit Edit

Nothing happens in browser window
JS console says:

```
PUT https://api.wordset.org/api/v1/proposals/5515c2513236370003ef0100 422 (Unprocessable Entity)
```

Screenshot:
![image](https://cloud.githubusercontent.com/assets/728042/6877772/841a94ba-d4d4-11e4-996a-5aadb1272271.png)

**Comment by malrase** [comment]
Hmm, was there always no example sentence there? I think the issue might be that the rails API expects an example sentence and we're not passing through the errors effectively!

**Comment by malrase** [comment]
OK. With my last commits I broke out the proposal edit stuff into a component. This means that if you leave the example sentence blank, an error will pop up above the textarea saying the example sentence is missing.

*However*, this isn't ideal – you can still hit the "Submit" button (it's still green, etc.), and the error will still appear. It's not the best UI. Tomorrow, Hampton and I will be working on getting a better solution out.

**Comment by hcatlin** [comment]
This depends on #14
