### ISSUE TITLE
Wordset logo is missing from header

### ISSUE THREAD

**Issue by BryanCode** [wordset/wordset-ui#121]
http://i.imgur.com/DOMUf8s.png
Issue is present on all pages; resolved on hard refresh.

**Comment by kaelig** [comment]
I can't reproduce this bug, can you clear your cache and try again?

**Comment by BryanCode** [comment]
I haven't been able to reproduce it either; it just happened that once. Go ahead and close the issue for now. I'll post if it happens again.

**Comment by kaelig** [comment]
Thanks. With the recent header changes it might totally have happened. Glad you reported it anyway.
