### ISSUE TITLE
This biology project is already done?

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset-ui#127]
I'm guessing this is a bug.

edit....

has style issues

<img width="712" alt="screen shot 2015-07-23 at 15 11 08" src="https://cloud.githubusercontent.com/assets/4720348/8851075/5411b674-314d-11e5-93da-f6ef9efab9e3.png">

**Comment by hcatlin** [comment]
It is! We did that a while ago....

**Comment by hcatlin** [comment]
The styles are off though.
