### ISSUE TITLE
Reasoning stays even after submission

### ISSUE THREAD

**Issue by zellerpress** [wordset/wordset-ui#138]
When going to a new word, after submitting a proposal, the reasoning for the last word/change stays in the box instead of clearing.

**Comment by interestinall** [comment]
I also experienced this.

**Comment by interestinall** [comment]
Also, the reasoning isn't displayed on the vote / edit view.

**Comment by sabreuse** [comment]
I've definitely seen Justin's issue (reasoning not displayed)

**Comment by hcatlin** [comment]
Just fixed this.
