### ISSUE TITLE
search autocomplete should be case-insensitive

### ISSUE THREAD

**Issue by sabreuse** [wordset/wordset-ui#139]
It's often worth keeping a distinction between capitalized and uncapitalized wordsets ("polish" and "Polish" are totally different in meaning, pronunciation, derivation...), but that doesn't mean searchers will know in advance that they need to enter capitalized words (or even which form to enter).

**Comment by malrase** [comment]
Note: this is similar to wordset/wordset#62

**Comment by interestinall** [comment]
fixed.
