### ISSUE TITLE
Front page 'random word button' is clipped

### ISSUE THREAD

**Issue by msingle** [wordset/wordset-ui#144]
Firefox 42.0a2 (though I saw it in stable) on Ubuntu 15.04

**Comment by msingle** [comment]
Firefox 42.0a2 (though I saw it in stable)

**Comment by interestinall** [comment]
hmm i can't replicate it on firefox 40.0.3

**Comment by msingle** [comment]
I can reproduce it with Firefox 40.0.3 (on Ubuntu)

**Comment by interestinall** [comment]
Invalid due to moving interfaces
