### ISSUE TITLE
"FAQs" and "Legal" links don't reset the scroll to the top

### ISSUE THREAD

**Issue by danielrw7** [wordset/wordset-ui#148]
Chrome v45.0.2454.93 and Firefox v42.0a2 on Windows 8.1

**Comment by interestinall** [comment]
Project goals and guidelines too now that I look.

Thanks for pointing this out :)

**Comment by danielrw7** [comment]
No problem. It looks like all of the "Latest Blog Posts" links and the links on https://www.wordset.org/posts do same.

**Comment by hcatlin** [comment]
Fixed from your pull request.
