### ISSUE TITLE
Hitting back button from random word page goes back two pages

### ISSUE THREAD

**Issue by danielrw7** [wordset/wordset-ui#156]
For example:

- Go to Project Goals
- Click on WORDSET logo (now at the home page)
- Click on "Give me a random word to improve!"
- Click back
- You now are all the way back to the Project Goals page, _not_ the home page

I have this issue on Chrome (45.0.2454.93) and Firefox (42.0a2)

**Comment by danielrw7** [comment]
`history.length` isn't changing between the homepage and the random word

**Comment by danielrw7** [comment]
The "Vote on a proposal" button works correctly (the back button takes you to the home page).

**Comment by hcatlin** [comment]
I believe your pull request fixes this.
