### ISSUE TITLE
When editing a definition it requires you fix errors on all definitions before submitting

### ISSUE THREAD

**Issue by jsatk** [wordset/wordset-ui#168]
I attempted to edit a definition. Some of the existing definitions didn't pass validation. I assume validation was added later after the definitions were created. I could not submit my fix for the one definition without fixing the others as well. This behavior may be intentional, however I thought it worth bringing up. 

Possible solution would be to patch for *only* the edited definition if you do not wish to force users to fix all currently failing definitions.

**Comment by interestinall** [comment]
Invalid due to moving interfaces
