### ISSUE TITLE
Words can't be tagged/labeled as technical terms

### ISSUE THREAD

**Issue by BryanCode** [wordset/wordset-ui#175]

**Comment by malrase** [comment]
We did this intentionally, as we thought that meanings – rather than a sequence of letters – are technical.

**Comment by BryanCode** [comment]
But what about a word like "sublingual." The word is medical. You wouldn't say the meaning is medical? Or at least that's how I see it.

**Comment by interestinall** [comment]
Invalid due to moving interfaces
