### ISSUE TITLE
Comments aren't directly visible

### ISSUE THREAD

**Issue by BryanCode** [wordset/wordset-ui#178]
This isn't a huge problem (and is sort of due to laziness), but you can't easily see comments without scrolling down. This becomes a problem because you can't easily see if there's discussion on any given proposal. Perhaps add the comments on top of the voting box or have a little banner that says "there are comments" or something like that?

**Comment by interestinall** [comment]
This will be fixed in the site redesign we are working on :D

**Comment by BryanCode** [comment]
Awesome :)
