### ISSUE TITLE
Beta's Chat window clips the bottom comment in firefox 44 

### ISSUE THREAD

**Issue by msingle** [wordset/wordset-ui#181]

**Comment by malrase** [comment]
Do you mind opening this in https://github.com/wordset/wordset/issues?

Cheers!

**Comment by malrase** [comment]
Actually, I'll just leave this open cause I think I found a fix.

Apparently FF does padding differently!
http://stackoverflow.com/questions/20624938/padding-bottom-is-ignored-in-firefox-and-ie-on-overflowing-elements-with-no-cont
