### ISSUE TITLE
Chat loads with the leaderboard visible underneath

### ISSUE THREAD

**Issue by knikki** [wordset/wordset-ui#4]
Attached image shows what I'm talking about here. A page refresh fixes the issue, but this happens almost every time I visit the site.

![wordset-chat](https://cloud.githubusercontent.com/assets/8378889/6699990/bfab4122-ccc4-11e4-8657-73a74402cf71.png)

**Comment by malrase** [comment]
I think with [this commit](https://github.com/wordset/wordset-ui/commit/62ed60a765b19e98d4e79b339e231ac6fcdaceb2) I fixed the problem: basically, instead of looping through a list there should only ever be three in the list.

Can you let me know if this fixes it?

**Comment by hcatlin** [comment]
Fixed.
