### ISSUE TITLE
Add more information to word proposal history

### ISSUE THREAD

**Issue by malrase** [wordset/wordset-ui#53]
The word proposal history should be more detailed: when a change was proposed, etc.

**Comment by interestinall** [comment]
I would include the user who made the last adjustment. I think ppl will like that :)

**Comment by malrase** [comment]
http://guides.emberjs.com/v1.10.0/cookbook/user_interface_and_interaction/displaying_formatted_dates_with_moment_js/

**Comment by malrase** [comment]
I added the date to the proposals. See here: https://www.wordset.org/en/denature/proposals
