### ISSUE TITLE
See skipped proposals

### ISSUE THREAD

**Issue by malrase** [wordset/wordset-ui#62]
A number of people have asked about "skipped proposal" lists. Hitting skip means you'll never see the proposal again, causing some proposals to languish in non-accepted hell.

**Comment by hcatlin** [comment]
Maybe skips expire?
Maybe we bring in new people to vote on them?

**Comment by interestinall** [comment]
I like the idea of skips expiring.

**Comment by malrase** [comment]
This is now fixed. When hitting "see next proposal," the person will see any "skipped" proposals before they are finished,
