### ISSUE TITLE
Difference between original and changes, currently red and green, should be worked over for the color blind.

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset-ui#77]

**Comment by malrase** [comment]
Good call. Do you think some weight changes to the font, or opacity, or new colours all together?

**Comment by sabreuse** [comment]
I'd suggest a strikethrough on the deletes -- it's commonly used, and it
reinforces the idea that it's a deletion (even for users with normal color
vision). Moving away from the red/green convention seems like it would
cause other confusions, and thinner weights and lower opacities bring their
own accessibility issues.

**Comment by malrase** [comment]
Really like that idea! Added it to the repo.
