### ISSUE TITLE
Clicking beside label checkboxes will mark them checked.

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset-ui#78]
This causes people to add labels unintentionally from time to time.

**Comment by malrase** [comment]
So this is a weird one. I actually made the labels *bigger* because it's easier to tap on them when you're on a phone. I can make them smaller if that's something people would like?

**Comment by hcatlin** [comment]
Maybe we can highlight that something changed when they click? Like, make it obvious tha their random clicking did something?
