### ISSUE TITLE
When adding new meaning, proposal only shows the first 40 meanings but some words have many more than that.

### ISSUE THREAD

**Issue by interestinall** [wordset/wordset-ui#79]
For example, cut only goes to 41 although it has 70+ meanings:

![screen shot 2015-07-01 at 13 20 42](https://cloud.githubusercontent.com/assets/4720348/8453357/1cb0bad2-1ff4-11e5-9445-d1b67e197b2c.png)

**Comment by hcatlin** [comment]
I think this was a space issue... maybe we can say "This word has 70 more meanings"

**Comment by malrase** [comment]
Nope, it's actually a part-of-speech issue. We currently only show existing meanings with the same pos as the proposal
