### ISSUE TITLE
Chat room cuts off after a certain point--can't see previous messages

### ISSUE THREAD

**Issue by BryanCode** [wordset/wordset-ui#97]

**Comment by malrase** [comment]
This was more a design decision. Technically all previous messages exist on the system. But how many messages should we show? 
Currently, we show 30 messages by default. What's the optimum? Obviously loading all isn't going to be useful/user-friendly.
Maybe we could load by time-period? As in – show all the previous messages from the past week (or few days?)

**Comment by BryanCode** [comment]
Load by time period sounds good. Could also be done so that once you scrolled past all 30 a new set of 30 load, so that you can control how much you want to load/see.

**Comment by interestinall** [comment]
Maybe a 24 hr time period? That would fix people missing out because of time zone differences.
